### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by ccc1924** [clonos/cp#7]
I build clonos on freebsd 11 following this [guide](https://clonos.tekroutine.com/installation_on_freebsd.html).

some log
```
2018/01/23 18:26:09 [error] 4986#100703: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /usr/local/www/clonos/php/db.php:149
Stack trace:
#0 /usr/local/www/clonos/php/clonos.php(2478): Db->selectAssoc('select id,usern...')
#1 /usr/local/www/clonos/php/clonos.php(368): ClonOS->userRegisterCheck(Array)
#2 /usr/local/www/clonos/php/clonos.php(183): ClonOS->login()
#3 /usr/local/www/clonos/public/json.php(12): ClonOS->__construct('/usr/local/www/...')
#4 {main}
  thrown in /usr/local/www/clonos/php/db.php on line 149" while reading response header from upstream, client: 192.168.0.21, server: , request: "POST /json.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "192.168.0.16", referrer: "http://192.168.0.16/overview/"
```

**Comment by olevole** [comment]
It seems you do not have a database with accounts. Initialization of the database occurs via:
~~~
git clone https://github.com/cbsd/cbsd-forms-clonos_database.git /usr/local/cbsd/modules/forms.d/clonos_database

+

cbsd initenv
~~~

After this operation default databases will be placed on:

_/var/db/clonos/clonos.sqlite_

you can check that this database exists and your web user has access there ?

E.g.:

~~~
su -m www -c 'sqlite3 /var/db/clonos/clonos.sqlite "SELECT username FROM auth_user"'
~~~

If web user is **www**.
This user should be in 'cbsd' group and /var/db/clonos/clonos.sqlite must have read/write access to the web user.

**Comment by ccc1924** [comment]
problem has sloved, thank you
